name: Deploy site files

on:
  push:
    branches:
      - main # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      - name: 迁出代码
        uses: actions/checkout@main # 第一步，下载代码仓库

      - name: 安装node.js
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 14.0.0
        
        # 安装依赖
      - name: 安装依赖
        run: npm install

      # 打包
      - name: 打包
        run: npm run docs:build

      # 上传到服务器
      - name: 发布到服务器
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # scp参数
          ARGS: "-avzr --delete"
          # 源目录
          SOURCE: "docs/.vuepress/dist/"
          # 服务器ip：换成你的服务器IP
          REMOTE_HOST: "${{ secrets.SSH_HOST }}"
          # 用户
          REMOTE_USER: "root"
          # 目标地址
          TARGET: "/home/www/my-blog"
